#!/bin/sh
#
echo "Content-type: text/html"
echo ""
command=`echo "$QUERY_STRING" | awk '{split($0,array,"&")} END{print array[1]}' | awk '{split($0,array,"=")} END{print array[2]}'`
date=`date`
ipadd=`ip route get 1 | awk '{print $NF;exit}'`
uptime=`uptime`


cat <<EOT
<!DOCTYPE html>
<html>
<head>
<title>Camera - WebUI</title>
<link rel="icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVQI12P4//8/AAX+Av7czFnnAAAAAElFTkSuQmCC">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
    font-size: 100%;
    font-family: Arial, Verdana, sans-serif;
    text-align: center;
}
</style>
</head>
<body>
<div>

<br />
RTSP stream Main: rtsp://$ipadd:544/vs0
<br />
RTSP stream Sub: rtsp://$ipadd:544/vs1
<br />
Snapshot: http://$ipadd:3000/snapshot.jpeg
<br />
<img id="snapshot" src="http://$ipadd:3000/preview.jpeg"/>
<br />
<br />
<button onclick="window.location.href='webui?command=ptzinit'" id="home">Init_PTZ</button>
<br />
<br />
</div>
<table style="margin: 0px auto;">
    <tr align="center">
        <td><button onclick="window.location.href='webui?command=ptzlu'">&#11017;</button></td>
        <td><button onclick="window.location.href='webui?command=ptzu'">&#11014;</button></td>
        <td><button onclick="window.location.href='webui?command=ptzru'">&#11016;</button></td>
    </tr>
    <tr align="center">
        <td><button onclick="window.location.href='webui?command=ptzl'">&#11013;</button></td>
        <td>PTZ</td>
        <td><button onclick="window.location.href='webui?command=ptzr'">&#10145;</button></td>
    </tr>
    <tr align="center">
        <td><button onclick="window.location.href='webui?command=ptzld'">&#11019;</button></td>
        <td><button onclick="window.location.href='webui?command=ptzd'">&#11015;</button></td>
        <td><button onclick="window.location.href='webui?command=ptzrd'">&#11018;</button></td>
    </tr>
</table>
<br />
For manual testing:<br />
<button onclick="window.location.href='webui?command=irinit'" id="irinit">Init_IR</button>
<br />
<br />
<button onclick="window.location.href='webui?command=iron'" id="irledson">IR Off [ Day ]</button>
<br />
<button onclick="window.location.href='webui?command=iroff'" id="irledsoff">IR On [ Night ]</button>
<br /><br />
Date - $date
<br />
IP Address - $ipadd
<br />
Uptime - $uptime
<br />
<br />

<script>
setInterval(function() { document.getElementById("snapshot").src = "http://$ipadd:3000/" + Math.round(Math.random()*100000) + ".jpeg"; }, 300);
</script>

</body>
</html>
EOT

 if [ "$command" = "irinit" ]; then
  echo "init_ir" > /tmp/ptz.daemon
 fi
 if [ "$command" = "iron" ]; then
  echo "set_ir_cut 1" > /tmp/ptz.daemon
 fi
 if [ "$command" = "iroff" ]; then
  echo "set_ir_cut 0" > /tmp/ptz.daemon
 fi
 if [ "$command" = "ptzinit" ]; then
  echo "init_ptz" > /tmp/ptz.daemon
 fi
 if [ "$command" = "ptzu" ]; then
  echo "up" > /tmp/ptz.daemon
 fi
 if [ "$command" = "ptzd" ]; then
  echo "down" > /tmp/ptz.daemon
 fi
 if [ "$command" = "ptzl" ]; then
  echo "left" > /tmp/ptz.daemon
 fi
 if [ "$command" = "ptzr" ]; then
  echo "right" > /tmp/ptz.daemon
 fi
 if [ "$command" = "ptzru" ]; then
  echo "right_up" > /tmp/ptz.daemon
 fi
 if [ "$command" = "ptzrd" ]; then
  echo "right_down" > /tmp/ptz.daemon
 fi
 if [ "$command" = "ptzlu" ]; then
  echo "left_up" > /tmp/ptz.daemon
 fi
 if [ "$command" = "ptzld" ]; then
  echo "left_down" > /tmp/ptz.daemon
 fi
